# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 22:17
from __future__ import unicode_literals

import core.account_manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('login', models.CharField(max_length=255, unique=True)),
                ('about_me', models.TextField()),
                ('love_lang', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', core.account_manager.UserManager()),
            ],
        ),
    ]
